"use client";

import { useState, useTransition } from "react";
import {
  Brain,
  Check,
  CheckCircle2,
  Loader2,
  Save,
  Sparkles,
  Target,
  TrendingUp,
  Users,
} from "lucide-react";
import type { GeneratedPlan } from "@/lib/elite/types";
import { applyGeneratedPlan } from "@/lib/elite/coach-actions";
import { cn } from "@/lib/utils";

const EXAMPLE = `Today we worked on scanning before receiving. Body shape needs to be quicker — he's still square-on when the ball arrives. Composure was better under pressure.

Homework:
200 wall passes
Watch Rodri clips on body orientation
Practice opening hips before the first touch`;

export function SessionNotesStudio({ playerId }: { playerId: string }) {
  const [notes, setNotes] = useState("");
  const [plan, setPlan] = useState<GeneratedPlan | null>(null);
  const [source, setSource] = useState<"ai" | "fallback" | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [saved, setSaved] = useState(false);
  const [isSaving, startSave] = useTransition();

  async function generate() {
    setLoading(true);
    setError(null);
    setSaved(false);
    try {
      const res = await fetch("/api/elite/ai/session-notes", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ playerId, notes }),
      });
      const data = await res.json();
      if (!res.ok) {
        setError(data.error === "notes_required" ? "Add a few notes first." : "Generation failed.");
        setLoading(false);
        return;
      }
      setPlan(data.plan);
      setSource(data.source);
    } catch {
      setError("Something went wrong. Try again.");
    }
    setLoading(false);
  }

  function save() {
    if (!plan) return;
    startSave(async () => {
      await applyGeneratedPlan(playerId, notes, plan);
      setSaved(true);
    });
  }

  return (
    <div className="elite-card overflow-hidden">
      <div className="border-b border-white/6 p-5 sm:p-6">
        <div className="flex items-center gap-2 text-[10px] font-semibold uppercase tracking-[0.2em] text-accent">
          <Brain className="h-4 w-4" /> AI session notes
        </div>
        <h3 className="mt-1 font-display text-2xl font-bold uppercase tracking-tight">
          Type the session. Get the whole plan.
        </h3>
        <p className="mt-1 text-sm text-white/50">
          Write notes in plain English. Strive AI drafts the weekly focus,
          homework, progress updates, and the parent report.
        </p>

        <textarea
          value={notes}
          onChange={(e) => setNotes(e.target.value)}
          rows={6}
          placeholder={EXAMPLE}
          className="mt-4 w-full resize-y rounded-2xl border border-white/10 bg-white/[0.03] px-4 py-3 text-sm leading-relaxed text-bone placeholder:text-white/25 focus:border-accent/40 focus:outline-none"
        />
        <div className="mt-3 flex flex-wrap items-center gap-3">
          <button
            onClick={generate}
            disabled={loading || notes.trim().length < 4}
            className="btn-accent px-5 py-3"
          >
            {loading ? (
              <Loader2 className="h-4 w-4 animate-spin" />
            ) : (
              <Sparkles className="h-4 w-4" />
            )}
            {loading ? "Generating…" : "Generate plan"}
          </button>
          {!notes && (
            <button
              onClick={() => setNotes(EXAMPLE)}
              className="btn-ghost text-xs"
            >
              Use an example
            </button>
          )}
          {error && <span className="text-sm text-red-400">{error}</span>}
        </div>
      </div>

      {plan && (
        <div className="space-y-5 p-5 sm:p-6">
          <div className="flex items-center justify-between">
            <div className="chip-accent">
              {source === "ai" ? "Generated by Strive AI" : "Draft (template)"}
            </div>
            {saved ? (
              <span className="flex items-center gap-1.5 text-sm font-medium text-accent">
                <CheckCircle2 className="h-4 w-4" /> Saved & applied
              </span>
            ) : (
              <button
                onClick={save}
                disabled={isSaving}
                className="btn px-4 py-2 text-sm"
              >
                {isSaving ? (
                  <Loader2 className="h-4 w-4 animate-spin" />
                ) : (
                  <Save className="h-4 w-4" />
                )}
                Save &amp; apply
              </button>
            )}
          </div>

          {/* Weekly focus */}
          <Block icon={Target} title="Weekly focus">
            <p className="text-lg font-medium text-bone">{plan.weekly_focus}</p>
          </Block>

          {/* Homework */}
          <Block icon={Check} title="Homework checklist">
            <ul className="space-y-2">
              {plan.homework.map((h, i) => (
                <li
                  key={i}
                  className="rounded-xl border border-white/8 bg-white/[0.02] p-3"
                >
                  <div className="flex items-center justify-between gap-3">
                    <span className="font-semibold text-bone">{h.title}</span>
                    <span className="chip shrink-0">{h.reps}</span>
                  </div>
                  <p className="mt-1 text-sm text-white/55">{h.exercise}</p>
                  {h.notes && (
                    <p className="mt-1 text-xs text-white/40">{h.notes}</p>
                  )}
                </li>
              ))}
            </ul>
          </Block>

          {/* Progress updates */}
          {plan.progress_updates.length > 0 && (
            <Block icon={TrendingUp} title="Progress updates">
              <div className="flex flex-wrap gap-2">
                {plan.progress_updates.map((p) => (
                  <span
                    key={p.metric}
                    className="inline-flex items-center gap-2 rounded-full border border-accent/25 bg-accent/[0.06] px-3 py-1.5 text-sm"
                  >
                    <span className="text-white/70">{p.metric}</span>
                    <span className="font-display font-bold text-accent">
                      {p.value}
                    </span>
                  </span>
                ))}
              </div>
            </Block>
          )}

          {/* Parent update */}
          <Block icon={Users} title="Parent update">
            <p className="text-sm leading-relaxed text-white/70">
              {plan.parent_update}
            </p>
          </Block>

          {/* Player summary */}
          <Block icon={Sparkles} title="For the player">
            <p className="text-sm leading-relaxed text-white/70">
              {plan.player_summary}
            </p>
          </Block>

          {/* Next objectives */}
          {plan.next_week_objectives.length > 0 && (
            <Block icon={Target} title="Next week's objectives">
              <ul className="space-y-1.5">
                {plan.next_week_objectives.map((o, i) => (
                  <li key={i} className="flex items-start gap-2 text-sm text-white/70">
                    <span className="mt-1.5 h-1.5 w-1.5 shrink-0 rounded-full bg-accent" />
                    {o}
                  </li>
                ))}
              </ul>
            </Block>
          )}
        </div>
      )}
    </div>
  );
}

function Block({
  icon: Icon,
  title,
  children,
}: {
  icon: typeof Target;
  title: string;
  children: React.ReactNode;
}) {
  return (
    <div>
      <div className="mb-2 flex items-center gap-2 text-[10px] font-semibold uppercase tracking-[0.2em] text-white/40">
        <Icon className="h-3.5 w-3.5" /> {title}
      </div>
      {children}
    </div>
  );
}
