import type {
  Achievement,
  Checkin,
  CoachNote,
  FilmUpload,
  Game,
  Homework,
  Message,
  ParentReport,
  Player,
  Progress,
  ProgressMetric,
  WeeklyPlan,
} from "./types";

// ---------------------------------------------------------------------------
// Strive Elite demo data.
//
// Powers the app in demo mode (no Supabase configured) and mirrors what the
// SQL seed inserts in production. Five realistic players, each with goals,
// homework, progress, film, notes, messages, weekly plans, parent reports,
// achievements, and statistics.
// ---------------------------------------------------------------------------

export const DEMO_COACH = {
  id: "coach-ramella",
  full_name: "Coach Yinka",
  email: "coach@strivesoccerfc.com",
  role: "coach" as const,
  avatar_color: "#D4AF37",
};

const now = new Date(); // demo dates stay fresh relative to today
function daysFromNow(d: number): string {
  const t = new Date(now);
  t.setDate(t.getDate() + d);
  return t.toISOString();
}

export const DEMO_PLAYERS: Player[] = [
  {
    id: "p-marcus",
    profile_id: "u-marcus",
    coach_id: DEMO_COACH.id,
    full_name: "Marcus Bello",
    avatar_color: "#D4AF37",
    age: 13,
    position: "Attacking Midfield",
    level: "Advanced",
    current_week: 7,
    today_focus: "Own your 1v1. Sell the fake, explode past",
    goals: [
      "Make the regional development squad by spring",
      "Two-footed under pressure",
      "Play a full game without losing composure",
    ],
    strengths: ["Close control", "Vision", "Work rate"],
    weaknesses: ["Weak foot finishing", "Slows down under a press", "Heading"],
    parent_name: "Adeola Bello",
    parent_email: "adeola@example.com",
    next_session_at: daysFromNow(2),
    last_session_at: daysFromNow(-3),
    joined_at: "2026-04-11",
    subscription_status: "active",
    club: "Riverside United U14",
    dominant_foot: "Right",
    coach_memory:
      "Responds to challenges, not repetition. Left-foot weakness is mental, not technical. He keeps skipping weak-foot reps. Tight hamstrings; keep the plyos controlled. Loves a target to beat.",
    onboarded_at: "2026-04-11T00:00:00.000Z",
  },
  {
    id: "p-sofia",
    profile_id: "u-sofia",
    coach_id: DEMO_COACH.id,
    full_name: "Sofia Marín",
    avatar_color: "#7CC7FF",
    age: 12,
    position: "Winger",
    level: "Competitive",
    current_week: 5,
    today_focus: "First touch out of your feet, into space",
    goals: [
      "Beat a defender 1v1 with confidence",
      "Sharper first touch at speed",
      "Score with both feet",
    ],
    strengths: ["Acceleration", "Fearless 1v1", "Left foot"],
    weaknesses: ["First touch under pressure", "Decision making in the final third", "Right foot"],
    parent_name: "Elena Marín",
    parent_email: "elena@example.com",
    next_session_at: daysFromNow(1),
    last_session_at: daysFromNow(-4),
    joined_at: "2026-05-02",
    subscription_status: "active",
  },
  {
    id: "p-diego",
    profile_id: "u-diego",
    coach_id: DEMO_COACH.id,
    full_name: "Diego Santos",
    avatar_color: "#FF9F7C",
    age: 15,
    position: "Centre Back",
    level: "Elite",
    current_week: 11,
    today_focus: "Body shape when defending the half-turn",
    goals: [
      "Sign with an academy by end of year",
      "Command the back line vocally",
      "Cleaner progressive passing",
    ],
    strengths: ["Aerial dominance", "Positioning", "Composure"],
    weaknesses: ["Turning speed", "Passing range under pressure", "Recovery pace"],
    parent_name: "Marisol Santos",
    parent_email: "marisol@example.com",
    next_session_at: daysFromNow(3),
    last_session_at: daysFromNow(-2),
    joined_at: "2026-02-18",
    subscription_status: "active",
  },
  {
    id: "p-aisha",
    profile_id: "u-aisha",
    coach_id: DEMO_COACH.id,
    full_name: "Aisha Kone",
    avatar_color: "#C9A7FF",
    age: 11,
    position: "Striker",
    level: "Developing",
    current_week: 3,
    today_focus: "Finish first-time. Don't take the extra touch",
    goals: [
      "Learn to shoot with laces cleanly",
      "Stop drifting out of the game",
      "Build confidence on the ball",
    ],
    strengths: ["Movement in the box", "Bravery", "Speed"],
    weaknesses: ["Shooting technique", "Confidence", "Ball mastery"],
    parent_name: "Fatou Kone",
    parent_email: "fatou@example.com",
    next_session_at: daysFromNow(4),
    last_session_at: daysFromNow(-5),
    joined_at: "2026-06-20",
    subscription_status: "trialing",
  },
  {
    id: "p-liam",
    profile_id: "u-liam",
    coach_id: DEMO_COACH.id,
    full_name: "Liam O'Connor",
    avatar_color: "#8FE3B0",
    age: 14,
    position: "Full Back",
    level: "Competitive",
    current_week: 6,
    today_focus: "Overlap timing. Arrive as the ball is played",
    goals: [
      "Become a threat going forward",
      "Sharper 1v1 defending",
      "Deliver a consistent cross",
    ],
    strengths: ["Stamina", "1v1 defending", "Attitude"],
    weaknesses: ["Crossing", "Weak foot", "Attacking decisions"],
    parent_name: "Sean O'Connor",
    parent_email: "sean@example.com",
    next_session_at: daysFromNow(2),
    last_session_at: daysFromNow(-6),
    joined_at: "2026-04-29",
    subscription_status: "active",
  },
];

const progressFor = (
  playerId: string,
  values: Record<ProgressMetric, [number, number]>
): Progress[] =>
  (Object.keys(values) as ProgressMetric[]).map((metric, i) => ({
    id: `${playerId}-prog-${i}`,
    player_id: playerId,
    metric,
    value: values[metric][0],
    prev_value: values[metric][1],
    updated_at: daysFromNow(-3),
  }));

export const DEMO_PROGRESS: Progress[] = [
  ...progressFor("p-marcus", {
    "Ball Mastery": [82, 74],
    "Weak Foot": [54, 48],
    Passing: [78, 72],
    Scanning: [71, 58],
    "Decision Making": [69, 61],
    Confidence: [80, 70],
    Speed: [73, 70],
  }),
  ...progressFor("p-sofia", {
    "Ball Mastery": [68, 60],
    "Weak Foot": [45, 40],
    Passing: [62, 58],
    Scanning: [55, 47],
    "Decision Making": [58, 50],
    Confidence: [74, 66],
    Speed: [86, 82],
  }),
  ...progressFor("p-diego", {
    "Ball Mastery": [79, 76],
    "Weak Foot": [70, 64],
    Passing: [84, 77],
    Scanning: [88, 80],
    "Decision Making": [86, 79],
    Confidence: [90, 85],
    Speed: [66, 63],
  }),
  ...progressFor("p-aisha", {
    "Ball Mastery": [42, 34],
    "Weak Foot": [30, 26],
    Passing: [48, 44],
    Scanning: [40, 33],
    "Decision Making": [44, 38],
    Confidence: [52, 40],
    Speed: [80, 78],
  }),
  ...progressFor("p-liam", {
    "Ball Mastery": [64, 60],
    "Weak Foot": [50, 43],
    Passing: [70, 65],
    Scanning: [67, 60],
    "Decision Making": [63, 57],
    Confidence: [72, 68],
    Speed: [77, 74],
  }),
];

const hw = (
  playerId: string,
  week: number,
  items: Array<
    Partial<Homework> & { title: string; exercise: string; reps: string }
  >
): Homework[] =>
  items.map((it, i) => ({
    id: `${playerId}-hw-${week}-${i}`,
    player_id: playerId,
    week,
    session: it.session ?? 1,
    title: it.title,
    exercise: it.exercise,
    reps: it.reps,
    duration_min: it.duration_min ?? 15,
    video_url: it.video_url ?? null,
    notes: it.notes ?? null,
    completed: it.completed ?? false,
    completed_at: it.completed ? (it.completed_at ?? daysFromNow(-1)) : null,
    sort: i,
  }));

// Real plyo warm-ups pulled straight from the live drill bank - same title,
// exercise text, reps, and hosted video every real session opens with.
const MANUS = "https://files.manuscdn.com/user_upload_by_module/session_file/310519663373072550";
const plyo = (variant: number) =>
  [
    {
      title: "Plyo warm-up: Bulgarian split jumps",
      exercise: "Rear foot up on a bench, bed edge, or sturdy step, front foot a full stride forward. Drop into the split squat and explode straight up off the front leg. Land soft and go straight into the next rep.",
      reps: "3 x 8 each leg",
      duration_min: 4,
      video_url: "/drills/plyo-bulgarian-split-jumps.mp4",
    },
    {
      title: "Plyo warm-up: Pogo jumps",
      exercise: "Feet hip width, hands relaxed. Jump as high as you can using only a slight knee bend, the bounce comes from your ankles and calves. Land and leave the ground again instantly.",
      reps: "3 x 15",
      duration_min: 4,
      video_url: "/drills/plyo-pogo-jumps.mp4",
    },
    {
      title: "Plyo warm-up: Squat jumps",
      exercise: "Feet shoulder width. Sink into a full squat, thighs at least parallel, then drive up and jump as high as you can. Land soft back into the squat and go again.",
      reps: "3 x 12",
      duration_min: 4,
      video_url: "/drills/plyo-squat-jumps.mp4",
    },
    {
      title: "Plyo warm-up: Alternating lunge jumps",
      exercise: "Start in a lunge, back knee just off the floor. Explode straight up and switch legs in the air, land soft in the lunge on the other side and go again without pausing.",
      reps: "3 x 6 each leg",
      duration_min: 4,
      video_url: "/drills/plyo-alternating-lunge-jumps.mp4",
    },
    {
      title: "Plyo warm-up: Single leg step down hops",
      exercise: "Stand on a low step or bottom stair on one leg. Step down, and the instant your foot touches the floor, hop straight up off that same leg. Step back up and repeat, then switch legs.",
      reps: "3 x 6 each leg",
      duration_min: 4,
      video_url: "/drills/plyo-single-leg-step-down-hops.mp4",
    },
    {
      title: "Plyo warm-up: Lateral hops over object",
      exercise: "Put a ball, shoe, or cone on the floor. On both feet, hop side to side over it without stopping between reps. Stay on the balls of your feet.",
      reps: "3 x 20 seconds",
      duration_min: 4,
      video_url: "/drills/plyo-lateral-hops.mp4",
    },
    {
      title: "Plyo warm-up: Broad jumps",
      exercise: "Feet shoulder width. Sink into a squat, swing your arms back, then explode forward and jump as far as you can. Stick the landing in a squat, hold for one second, reset, and go again.",
      reps: "3 x 5",
      duration_min: 4,
      video_url: "/drills/plyo-broad-jumps.mp4",
    },
  ][(variant - 1) % 7];

export const DEMO_HOMEWORK: Homework[] = [
  ...hw("p-marcus", 5, [
    { ...plyo(1), session: 1, completed: true, completed_at: daysFromNow(-11) },
    {
      title: "Wall juggles",
      exercise: "Face a wall a few yards back. Volley the ball against the wall, let it come off, control it out of the air with one touch, then strike it back. Two touches maximum every time.",
      reps: "3 x 45 sec on, 30 sec rest",
      duration_min: 8,
      session: 1,
      completed: true,
      completed_at: daysFromNow(-11),
      video_url: "/drills/wall-juggles.mp4",
    },
    {
      title: "Wall pass, touch, scissor",
      exercise: "Cone a few feet in front of a wall. Pass into the wall, take a touch off the return, hit a scissor over the ball, then touch across to the other side of the cone and pass again. Work both feet.",
      reps: "3 x 90 sec, rest 30 sec",
      duration_min: 6,
      session: 1,
      completed: true,
      completed_at: daysFromNow(-11),
      video_url: "/drills/wall-pass-touch-scissor.mp4",
    },
    {
      title: "Wall pass, touch, stepover",
      exercise: "Same setup as the scissor version. Pass into the wall, take a touch off the return, hit a stepover, then touch across to the other side of the cone and pass again. Work both feet.",
      reps: "3 x 90 sec, rest 30 sec",
      duration_min: 6,
      session: 1,
      completed: true,
      completed_at: daysFromNow(-11),
      video_url: "/drills/wall-pass-touch-stepover.mp4",
    },
    { ...plyo(2), session: 2, completed: true, completed_at: daysFromNow(-10) },
    {
      title: "L turn, pullback, chop",
      exercise: "Two cones two feet apart. Work the ball through the pattern: L turn at the first cone, pullback, then chop across to the other cone. Keep the sequence flowing without stopping.",
      reps: "3 x 1 min, rest 30 sec",
      duration_min: 5,
      session: 2,
      completed: true,
      completed_at: daysFromNow(-10),
      video_url: "/drills/l-turn-pullback-chop.mp4",
    },
    {
      title: "Push pull, fake roll, roll across",
      exercise: "Same two cones two feet apart. Push pull at the first cone, sell the fake roll, then roll the ball across to the other cone and repeat the sequence the other way.",
      reps: "3 x 1 min, rest 30 sec",
      duration_min: 5,
      session: 2,
      completed: true,
      completed_at: daysFromNow(-10),
      video_url: "/drills/push-pull-fake-roll.mp4",
    },
    {
      title: "Body Feint",
      exercise: "One cone as the defender, 10 yards of run-up. Dribble at the cone, plant and dip your shoulder one way, take the ball the other way with the outside of the opposite foot.",
      reps: "3 x 12 each side, rest 45 sec",
      duration_min: 9,
      session: 2,
      completed: true,
      completed_at: daysFromNow(-10),
      video_url: `${MANUS}/DwIDNpPWjIfESEPa.MP4`,
    },
    { ...plyo(3), session: 3, completed: true, completed_at: daysFromNow(-9) },
    {
      title: "3 cone passing drill, inside touch",
      exercise: "Three cones in a line a few feet from a wall, making two gaps. Pass through a gap into the wall, take an inside touch across your body to line up the next gap, and pass through that one.",
      reps: "3 x 90 sec, rest 30 sec",
      duration_min: 6,
      session: 3,
      completed: true,
      completed_at: daysFromNow(-9),
      video_url: "/drills/wall-pass-inside-touch-shuttle.mp4",
    },
    {
      title: "3 cone passing drill, outside touch",
      exercise: "Same setup, OUTSIDE-of-the-foot touch to line up the next gap, and pass through that one. Work back and forth, then switch which foot plays the pass.",
      reps: "3 x 90 sec, rest 30 sec",
      duration_min: 6,
      session: 3,
      completed: true,
      completed_at: daysFromNow(-9),
      video_url: "/drills/wall-pass-outside-touch-shuttle.mp4",
    },
    {
      title: "Two touch passing",
      exercise: "One cone a few feet from a wall. Pass into the wall with the inside of your foot, take one touch across to the other side of the cone, and pass again with the other foot.",
      reps: "3 x 90 sec, rest 30 sec",
      duration_min: 6,
      session: 3,
      completed: true,
      completed_at: daysFromNow(-9),
      video_url: "/drills/two-touch-passing.mp4",
    },
    { ...plyo(4), session: 4, completed: true, completed_at: daysFromNow(-8) },
    {
      title: "Neymar Feint",
      exercise: "Open space or a single cone as the defender. Dribble forward, stop abruptly, and drop your shoulder in the opposite direction. Explode forward past the defender.",
      reps: "3 x 12 each side, rest 45 sec",
      duration_min: 9,
      session: 4,
      completed: true,
      completed_at: daysFromNow(-8),
      video_url: `${MANUS}/oFUpYSVfdHkZMtUl.MP4`,
    },
    {
      title: "Maradona",
      exercise: "One cone as the defender. Dribble in, stop the ball with one sole, spin 180 over it, drag it away with the other sole and accelerate out.",
      reps: "3 x 12 each side, rest 45 sec",
      duration_min: 9,
      session: 4,
      completed: true,
      completed_at: daysFromNow(-8),
      video_url: `${MANUS}/rLwklYeePleghSHY.MP4`,
    },
    {
      title: "Mbappe Chop",
      exercise: "One cone as the defender, attack it with speed. Light hop and chop the ball behind your plant leg with the inside of the foot, cutting across the defender.",
      reps: "3 x 12 each side, rest 45 sec",
      duration_min: 9,
      session: 4,
      completed: true,
      completed_at: daysFromNow(-8),
      video_url: `${MANUS}/NTNYbFKFgaMEpxiA.MP4`,
    },
  ]),
  ...hw("p-marcus", 6, [
    { ...plyo(5), session: 1, completed: true, completed_at: daysFromNow(-6) },
    {
      title: "Two touch passing, outside touch",
      exercise: "Same setup as two touch passing. Pass into the wall, take the touch across the cone with the OUTSIDE of your foot, and pass again.",
      reps: "3 x 90 sec, rest 30 sec",
      duration_min: 6,
      session: 1,
      completed: true,
      completed_at: daysFromNow(-6),
      video_url: "/drills/two-touch-passing-outside.mp4",
    },
    {
      title: "Pass, touch past, Cruyff turn",
      exercise: "Two cones 3 to 5 feet apart, a few feet from a wall. Pass through the gap into the wall, take the return touch past one cone, Cruyff turn back into the space, and pass to the wall again.",
      reps: "3 x 90 sec, rest 30 sec",
      duration_min: 6,
      session: 1,
      completed: true,
      completed_at: daysFromNow(-6),
      video_url: "/drills/pass-cruyff-turn.mp4",
    },
    {
      title: "Pass, touch past, Cruyff turn, outside touch",
      exercise: "Same setup, OUTSIDE of the foot on the return touch, Cruyff turn back into the space, and pass to the wall again. Repeat out the other side.",
      reps: "3 x 90 sec, rest 30 sec",
      duration_min: 6,
      session: 1,
      completed: true,
      completed_at: daysFromNow(-6),
      video_url: "/drills/pass-cruyff-turn-outside.mp4",
    },
    { ...plyo(6), session: 2, completed: true, completed_at: daysFromNow(-5) },
    {
      title: "La Croqueta cone weave",
      exercise: "Line of 5 cones a yard apart. La croqueta at every cone: quick shift foot to foot, glide past. Both directions.",
      reps: "5 x 45 sec on, 45 sec off",
      duration_min: 8,
      session: 2,
      completed: true,
      completed_at: daysFromNow(-5),
      video_url: `${MANUS}/POoQopaTzkWqvXpv.mov`,
    },
    {
      title: "Inside-outside cone weave",
      exercise: "Line of 5 cones a yard apart. Weave through with inside and outside of the foot only, tight touches.",
      reps: "6 x 45 sec on, 45 sec off",
      duration_min: 9,
      session: 2,
      completed: true,
      completed_at: daysFromNow(-5),
      video_url: `${MANUS}/vwzCCVyDFkTUIZfq.mp4`,
    },
    {
      title: "1v1 freestyle",
      exercise: "One cone as the defender, full run-up. Dribble at it with speed, sell any move from the library right at the cone, explode past.",
      reps: "5 x 8 full speed, walk-back reset",
      duration_min: 10,
      session: 2,
      completed: true,
      completed_at: daysFromNow(-5),
      video_url: `${MANUS}/isWTvYFmpepwbekU.mp4`,
    },
    { ...plyo(7), session: 3, completed: true, completed_at: daysFromNow(-4) },
    {
      title: "3 cone turning drill",
      exercise: "Three cones in a triangle a few feet from a wall, one back cone and two front cones. Pass into the wall, take an inside touch around a front cone, lap around the back cone, and pass again.",
      reps: "3 x 90 sec, rest 30 sec",
      duration_min: 6,
      session: 3,
      completed: true,
      completed_at: daysFromNow(-4),
      video_url: "/drills/triangle-turning.mp4",
    },
    {
      title: "3 cone turning drill, outside touch",
      exercise: "Same triangle, turn around a front cone with the OUTSIDE of your foot, lap around the back cone, and pass again. Repeat out the other side.",
      reps: "3 x 90 sec, rest 30 sec",
      duration_min: 6,
      session: 3,
      completed: true,
      completed_at: daysFromNow(-4),
      video_url: "/drills/triangle-turning-outside.mp4",
    },
    {
      title: "Wall pass, touch behind the leg",
      exercise: "Cone a few feet in front of a wall. Pass into the wall, then take the return touch behind your standing leg to the other side of the cone and pass again. Work both feet.",
      reps: "3 x 90 sec, rest 30 sec",
      duration_min: 6,
      session: 3,
      completed: true,
      completed_at: daysFromNow(-4),
      video_url: "/drills/wall-pass-behind-the-leg.mp4",
    },
    { ...plyo(1), session: 4, completed: true, completed_at: daysFromNow(-3) },
    {
      title: "La Croqueta",
      exercise: "One cone as the defender. Dribble at it and shift the ball from one foot to the other in one quick motion, sliding past the cone.",
      reps: "3 x 12 each side, rest 45 sec",
      duration_min: 9,
      session: 4,
      completed: true,
      completed_at: daysFromNow(-3),
      video_url: `${MANUS}/cJyFfcoIukyYuKOl.MP4`,
    },
    {
      title: "Elastico",
      exercise: "One cone as the defender. Push the outside of your foot into the ball, then snap it back inside in one fluid touch and go past.",
      reps: "3 x 12 each side, rest 45 sec",
      duration_min: 9,
      session: 4,
      completed: true,
      completed_at: daysFromNow(-3),
      video_url: `${MANUS}/fSpCzUHlZbnqCRAW.mp4`,
    },
    {
      title: "Reverse Elastico",
      exercise: "One cone as the defender. Fake inside with the inside of the foot, then snap the ball outside in one motion and accelerate away.",
      reps: "3 x 12 each side, rest 45 sec",
      duration_min: 9,
      session: 4,
      completed: true,
      completed_at: daysFromNow(-3),
      video_url: `${MANUS}/LUrnPLriXaIbxhDG.mp4`,
    },
  ]),
  ...hw("p-marcus", 7, [
    { ...plyo(2), session: 1, completed: true, completed_at: daysFromNow(-2) },
    {
      title: "Wall pass, touch, L turn",
      exercise: "Cone a few feet in front of a wall. Pass into the wall, take a touch off the return, L turn behind your standing leg to the other side of the cone, and pass again. Work both feet.",
      reps: "3 x 90 sec, rest 30 sec",
      duration_min: 6,
      session: 1,
      completed: true,
      completed_at: daysFromNow(-2),
      video_url: "/drills/wall-pass-l-turn.mp4",
    },
    {
      title: "Wall juggles",
      exercise: "Face a wall a few yards back. Volley the ball against the wall, let it come off, control it out of the air with one touch, then strike it back.",
      reps: "3 x 45 sec on, 30 sec rest",
      duration_min: 8,
      session: 1,
      completed: true,
      completed_at: daysFromNow(-2),
      video_url: "/drills/wall-juggles.mp4",
    },
    {
      title: "Wall pass, touch, scissor",
      exercise: "Cone a few feet in front of a wall. Pass into the wall, take a touch off the return, hit a scissor over the ball, then touch across to the other side of the cone and pass again.",
      reps: "3 x 90 sec, rest 30 sec",
      duration_min: 6,
      session: 1,
      completed: true,
      completed_at: daysFromNow(-2),
      video_url: "/drills/wall-pass-touch-scissor.mp4",
    },
    { ...plyo(3), session: 2, completed: true, completed_at: daysFromNow(-1) },
    {
      title: "8-cone freestyle",
      exercise: "8 cones scattered in a box. Free dribble, every surface of both feet, one skill move at each cone you pass.",
      reps: "5 x 60 sec on, 45 sec off",
      duration_min: 9,
      session: 2,
      completed: true,
      completed_at: daysFromNow(-1),
      video_url: `${MANUS}/QiblJbEqVTPozDud.mp4`,
    },
    {
      title: "Ronaldinho drill",
      exercise: "Ball at your feet, small space. Inside-touch inside-touch between the feet, then a sole roll to reset. Steady rhythm.",
      reps: "4 x 60 sec on, 30 sec off",
      duration_min: 8,
      session: 2,
      completed: true,
      completed_at: daysFromNow(-1),
      video_url: `${MANUS}/sSDCRAmGquYZMddQ.mp4`,
    },
    {
      title: "Figure-8 dribble",
      exercise: "Two cones two yards apart. Tight figure-8 through them, close touches both feet.",
      reps: "6 x 45 sec on, 45 sec off",
      duration_min: 9,
      session: 2,
      completed: true,
      completed_at: daysFromNow(-1),
      video_url: `${MANUS}/hTHXbVErXMeegCGE.mp4`,
    },
    { ...plyo(4), session: 3 },
    {
      title: "Wall pass, touch, stepover",
      exercise: "Cone a few feet in front of a wall. Pass into the wall, take a touch off the return, hit a stepover, then touch across to the other side of the cone and pass again.",
      reps: "3 x 90 sec, rest 30 sec",
      duration_min: 6,
      session: 3,
      video_url: "/drills/wall-pass-touch-stepover.mp4",
      notes: "This is the week the stepover becomes automatic. Sell it with your hips, not just your feet.",
    },
    {
      title: "3 cone passing drill, inside touch",
      exercise: "Three cones in a line a few feet from a wall, making two gaps. Pass through a gap into the wall, take an inside touch across your body to line up the next gap, and pass through that one.",
      reps: "3 x 90 sec, rest 30 sec",
      duration_min: 6,
      session: 3,
      video_url: "/drills/wall-pass-inside-touch-shuttle.mp4",
    },
    {
      title: "Two touch passing",
      exercise: "One cone a few feet from a wall. Pass into the wall with the inside of your foot, take one touch across to the other side of the cone, and pass again with the other foot.",
      reps: "3 x 90 sec, rest 30 sec",
      duration_min: 6,
      session: 3,
      video_url: "/drills/two-touch-passing.mp4",
    },
    { ...plyo(5), session: 4 },
    {
      title: "Push pull, fake roll, roll across",
      exercise: "Same two cones two feet apart. Push pull at the first cone, sell the fake roll, then roll the ball across to the other cone and repeat the sequence the other way.",
      reps: "3 x 1 min, rest 30 sec",
      duration_min: 5,
      session: 4,
      video_url: "/drills/push-pull-fake-roll.mp4",
    },
    {
      title: "L turn, pullback, chop",
      exercise: "Two cones two feet apart. Work the ball through the pattern: L turn at the first cone, pullback, then chop across to the other cone.",
      reps: "3 x 1 min, rest 30 sec",
      duration_min: 5,
      session: 4,
      video_url: "/drills/l-turn-pullback-chop.mp4",
    },
    {
      title: "Body Feint",
      exercise: "One cone as the defender, 10 yards of run-up. Dribble at the cone, plant and dip your shoulder one way, take the ball the other way with the outside of the opposite foot.",
      reps: "3 x 12 each side, rest 45 sec",
      duration_min: 9,
      session: 4,
      video_url: `${MANUS}/DwIDNpPWjIfESEPa.MP4`,
    },
  ]),
  ...hw("p-sofia", 5, [
    {
      title: "Two touch passing",
      exercise: "One cone a few feet from a wall. Pass into the wall with the inside of your foot, take one touch across to the other side of the cone, and pass again with the other foot.",
      reps: "3 x 90 sec, rest 30 sec",
      duration_min: 6,
      completed: true,
      video_url: "/drills/two-touch-passing.mp4",
    },
    {
      title: "Wall pass, touch, stepover",
      exercise: "Cone a few feet in front of a wall. Pass into the wall, take a touch off the return, hit a stepover, then touch across to the other side of the cone and pass again.",
      reps: "3 x 90 sec, rest 30 sec",
      duration_min: 6,
      video_url: "/drills/wall-pass-touch-stepover.mp4",
    },
    {
      title: "Wall pass, touch, L turn",
      exercise: "Cone a few feet in front of a wall. Pass into the wall, take a touch off the return, L turn behind your standing leg to the other side of the cone, and pass again.",
      reps: "3 x 90 sec, rest 30 sec",
      duration_min: 6,
      video_url: "/drills/wall-pass-l-turn.mp4",
    },
  ]),
  ...hw("p-diego", 11, [
    {
      title: "3 cone turning drill",
      exercise: "Three cones in a triangle a few feet from a wall. Pass into the wall, take an inside touch around a front cone, lap around the back cone, and pass again.",
      reps: "3 x 90 sec, rest 30 sec",
      duration_min: 6,
      completed: true,
      video_url: "/drills/triangle-turning.mp4",
    },
    {
      title: "3 cone turning drill, outside touch",
      exercise: "Same triangle, turn around a front cone with the OUTSIDE of your foot, lap around the back cone, and pass again.",
      reps: "3 x 90 sec, rest 30 sec",
      duration_min: 6,
      completed: true,
      video_url: "/drills/triangle-turning-outside.mp4",
    },
    {
      title: "Wall pass, touch behind the leg",
      exercise: "Cone a few feet in front of a wall. Pass into the wall, then take the return touch behind your standing leg to the other side of the cone and pass again.",
      reps: "3 x 90 sec, rest 30 sec",
      duration_min: 6,
      video_url: "/drills/wall-pass-behind-the-leg.mp4",
    },
  ]),
  ...hw("p-aisha", 3, [
    {
      title: "Ronaldinho drill",
      exercise: "Ball at your feet, small space. Inside-touch inside-touch between the feet, then a sole roll to reset. Steady rhythm.",
      reps: "4 x 60 sec on, 30 sec off",
      duration_min: 8,
      video_url: `${MANUS}/sSDCRAmGquYZMddQ.mp4`,
    },
    {
      title: "Body Feint",
      exercise: "One cone as the defender, 10 yards of run-up. Dribble at the cone, plant and dip your shoulder one way, take the ball the other way with the outside of the opposite foot.",
      reps: "3 x 12 each side, rest 45 sec",
      duration_min: 9,
      completed: true,
      video_url: `${MANUS}/DwIDNpPWjIfESEPa.MP4`,
    },
    {
      title: "Neymar Feint",
      exercise: "Open space or a single cone as the defender. Dribble forward, stop abruptly, and drop your shoulder in the opposite direction. Explode forward past the defender.",
      reps: "3 x 12 each side, rest 45 sec",
      duration_min: 9,
      video_url: `${MANUS}/oFUpYSVfdHkZMtUl.MP4`,
    },
  ]),
  ...hw("p-liam", 6, [
    {
      title: "Pass, touch past, Cruyff turn",
      exercise: "Two cones 3 to 5 feet apart, a few feet from a wall. Pass through the gap into the wall, take the return touch past one cone, Cruyff turn back into the space, and pass to the wall again.",
      reps: "3 x 90 sec, rest 30 sec",
      duration_min: 6,
      completed: true,
      video_url: "/drills/pass-cruyff-turn.mp4",
    },
    {
      title: "Wall pass, touch behind the leg",
      exercise: "Cone a few feet in front of a wall. Pass into the wall, then take the return touch behind your standing leg to the other side of the cone and pass again.",
      reps: "3 x 90 sec, rest 30 sec",
      duration_min: 6,
      video_url: "/drills/wall-pass-behind-the-leg.mp4",
    },
    {
      title: "Wall pass, touch, L turn",
      exercise: "Cone a few feet in front of a wall. Pass into the wall, take a touch off the return, L turn behind your standing leg to the other side of the cone, and pass again.",
      reps: "3 x 90 sec, rest 30 sec",
      duration_min: 6,
      video_url: "/drills/wall-pass-l-turn.mp4",
    },
  ]),
];

export const DEMO_FILM: FilmUpload[] = [
  {
    id: "f-marcus-1",
    player_id: "p-marcus",
    month: 1,
    title: "League game vs. Riverside, first half",
    url: null,
    thumbnail: null,
    coach_notes:
      "You played brave, Marcus. That's the headline. Six take-ons attempted, four clean.",
    review: {
      summary:
        "You played brave, Marcus. That's the headline. Six take-ons attempted, four clean. Most players your age pass backwards the second a defender steps up; you attacked. What we build now is what happens after the move - the first two steps decide whether a beaten defender stays beaten.",
      moments: [
        {
          time: "04:12",
          note: "Body feint, pushed past the fullback on your first touch. That's the exact move we've been drilling. Straight game transfer.",
          kind: "good",
        },
        {
          time: "12:30",
          note: "Runner in behind and you never scanned. Two looks before the ball arrives and that's an assist.",
          kind: "fix",
        },
        {
          time: "19:47",
          note: "Took it on the half-turn under pressure and escaped left. Pure composure.",
          kind: "good",
        },
        {
          time: "26:05",
          note: "Beat your man clean, then slowed down and let him recover. Finish the move: burst for two steps after every take-on.",
          kind: "fix",
        },
      ],
      strengths: [
        "Take-on bravery: 6 attempted, 4 clean. That ratio is rare at your age.",
        "First touch under pressure: you kill the ball instead of panicking.",
        "The right-side body feint is already game-real.",
      ],
      fixes: [
        "Exit speed: the move beats the defender, the burst keeps him beaten.",
        "Left-side escapes: you exited right on 5 of your 6 take-ons. Defenders will learn that.",
        "Scanning before you receive in the final third.",
      ],
      next_steps: [
        "Every take-on rep this week ends with a two-step burst. No exceptions.",
        "The left-exit work in your plan is there because of this film. Own it.",
        "Film your next league game. I'm counting your left exits.",
      ],
    },
    status: "Reviewed",
    created_at: daysFromNow(-33),
  },
  {
    id: "f-marcus-2",
    player_id: "p-marcus",
    month: 2,
    title: "League game vs. Arlington, second half",
    url: null,
    thumbnail: null,
    coach_notes: null,
    status: "Uploaded",
    created_at: daysFromNow(-1),
  },
  {
    id: "f-sofia-1",
    player_id: "p-sofia",
    title: "1v1 clips from training",
    url: null,
    thumbnail: null,
    coach_notes:
      "Your acceleration is elite. First touch on 3 of 6 was heavy. Push it further into space and you're gone.",
    status: "Reviewed",
    created_at: daysFromNow(-5),
  },
  {
    id: "f-diego-1",
    player_id: "p-diego",
    title: "Academy trial, full game",
    url: null,
    thumbnail: null,
    coach_notes:
      "Dominant in the air. One turn at 38:00 you got caught. Trust the early body shape.",
    status: "Analyzing",
    created_at: daysFromNow(-2),
  },
];

export const DEMO_NOTES: CoachNote[] = [
  {
    id: "n-marcus-1",
    player_id: "p-marcus",
    body: "Marcus is turning a corner mentally. Scanning is becoming automatic. Next block: weak-foot finishing under fatigue.",
    created_at: daysFromNow(-3),
  },
  {
    id: "n-sofia-1",
    player_id: "p-sofia",
    body: "Fearless in 1v1. If we sharpen the first touch she's a real problem for defenders. Confidence is high. Keep feeding it.",
    created_at: daysFromNow(-4),
  },
];

export const DEMO_MESSAGES: Message[] = [
  {
    id: "m-marcus-1",
    player_id: "p-marcus",
    from_role: "coach",
    from_name: "Coach Yinka",
    body: "Your stepover is winning you space every single rep now. This week we chain it: stepover into the chop, full speed. Defenders can stop one move. They can't stop two.",
    created_at: daysFromNow(-2),
    read: false,
  },
  {
    id: "m-sofia-1",
    player_id: "p-sofia",
    from_role: "coach",
    from_name: "Coach Yinka",
    body: "Your acceleration is unfair. Let's make that first touch just as scary. See you tomorrow.",
    created_at: daysFromNow(-1),
    read: false,
  },
  {
    id: "m-diego-1",
    player_id: "p-diego",
    from_role: "coach",
    from_name: "Coach Yinka",
    body: "Academy scout was impressed. Keep commanding that back line. Full breakdown of your trial film coming today.",
    created_at: daysFromNow(-1),
    read: true,
  },
  {
    id: "m-aisha-1",
    player_id: "p-aisha",
    from_role: "coach",
    from_name: "Coach Yinka",
    body: "You were braver in the box last session. I saw it. Keep finishing first-time and the goals will come.",
    created_at: daysFromNow(-2),
    read: false,
  },
  {
    id: "m-liam-1",
    player_id: "p-liam",
    from_role: "coach",
    from_name: "Coach Yinka",
    body: "Your crossing is getting sharp. This week we time the overlaps. Big season ahead.",
    created_at: daysFromNow(-3),
    read: true,
  },
];

export const DEMO_GAMES: Game[] = [
  {
    id: "g-marcus-1",
    player_id: "p-marcus",
    game_date: daysFromNow(4).slice(0, 10),
    kickoff: "10:30 AM",
    opponent: "Loudoun United U14",
    location: "Haymarket, VA",
    notes: "League game, starting CAM",
    coach_attending: true,
    created_at: daysFromNow(-2),
  },
  {
    id: "g-marcus-2",
    player_id: "p-marcus",
    game_date: daysFromNow(11).slice(0, 10),
    kickoff: "1:00 PM",
    opponent: "Arlington SA",
    location: "Arlington, VA",
    notes: "",
    coach_attending: false,
    created_at: daysFromNow(-1),
  },
];

export const DEMO_CHECKINS: Checkin[] = [
  {
    id: "ci-marcus-7",
    player_id: "p-marcus",
    week: 6,
    rating: 4,
    energy: 3,
    went_well: "Scanning is becoming automatic. I caught myself checking both shoulders without thinking.",
    struggled: "Left-foot exits still feel a step slow.",
    note: "Legs a bit heavy midweek but pushed through all four sessions.",
    coach_feedback:
      "That croqueta click is real. I can see it. Left-foot exits get slow reps this week; speed comes after clean.",
    coach_feedback_at: daysFromNow(-2),
    created_at: daysFromNow(-3),
  },
  {
    id: "ci-marcus-6",
    player_id: "p-marcus",
    week: 5,
    rating: 3,
    energy: 4,
    went_well: "The croqueta finally clicked. Both directions.",
    struggled: "Got frustrated with the weak-foot reps and rushed them.",
    note: "",
    coach_feedback: "",
    coach_feedback_at: null,
    created_at: daysFromNow(-10),
  },
];

export const DEMO_WEEKLY_PLANS: WeeklyPlan[] = [
  {
    id: "wp-marcus-7",
    player_id: "p-marcus",
    week: 7,
    focus: "Chain your moves at game speed",
    objectives: [
      "Croqueta at full speed, both directions",
      "Two-move chains without slowing down",
      "Every exit touch on the weak foot",
    ],
    homework: [
      { title: "Croqueta + burst: test day", exercise: "Twelve clean at full speed, each way", reps: "24" },
      { title: "Left-exit chains", exercise: "Any move, every exit touch left-footed, then burst", reps: "14" },
    ],
    created_at: daysFromNow(-3),
  },
];

export const DEMO_PARENT_REPORTS: ParentReport[] = [
  {
    id: "pr-marcus-1",
    player_id: "p-marcus",
    summary:
      "This week Marcus worked on scanning before receiving and staying composed under a press. His decision-making is visibly sharper.",
    improvement:
      "Scanning jumped from 58 to 71. He's now checking his shoulder automatically, a habit that separates good players from great ones.",
    homework:
      "Two-move chains at game speed, left-foot exits, and a film study on deciding late in 1v1s.",
    next_focus:
      "Weak-foot finishing under fatigue and playing forward on the half-turn.",
    created_at: daysFromNow(-3),
  },
];

// Every demo badge mirrors the real achievement engine in
// lib/elite/achievements.ts — same titles, same details, all provable
// from tracked training data. No made-up trophies.
export const DEMO_ACHIEVEMENTS: Achievement[] = [
  {
    id: "a-marcus-1",
    player_id: "p-marcus",
    title: "3 Perfect Weeks",
    detail: "Three straight weeks at 100%",
    icon: "Trophy",
    earned_at: daysFromNow(-2),
  },
  {
    id: "a-marcus-2",
    player_id: "p-marcus",
    title: "7-Day Streak",
    detail: "Trained seven days in a row",
    icon: "Flame",
    earned_at: daysFromNow(-9),
  },
  {
    id: "a-marcus-3",
    player_id: "p-marcus",
    title: "Week Conquered",
    detail: "Every drill in a week, done",
    icon: "CheckCircle2",
    earned_at: daysFromNow(-16),
  },
  {
    id: "a-sofia-1",
    player_id: "p-sofia",
    title: "Week Conquered",
    detail: "Every drill in a week, done",
    icon: "CheckCircle2",
    earned_at: daysFromNow(-4),
  },
  {
    id: "a-diego-1",
    player_id: "p-diego",
    title: "7-Day Streak",
    detail: "Trained seven days in a row",
    icon: "Flame",
    earned_at: daysFromNow(-2),
  },
  {
    id: "a-aisha-1",
    player_id: "p-aisha",
    title: "First Session",
    detail: "Your first full session, done",
    icon: "Sparkles",
    earned_at: daysFromNow(-3),
  },
];

// The player the demo "player login" signs in as.
export const DEMO_PLAYER_ID = "p-marcus";
