import type {
  CoachTask,
  ContentItem,
  CourseModule,
  Lead,
  Player,
  Session,
} from "./types";

const COLORS = ["#E5FF3D", "#FF6B6B", "#5EE2C9", "#7C9CFF", "#FFB86B", "#C77DFF"];
const color = (i: number) => COLORS[i % COLORS.length];

export const players: Player[] = [
  {
    id: "p_001",
    name: "Marcus Adeyemi",
    age: 11,
    parentName: "Tope Adeyemi",
    parentEmail: "tope@example.com",
    parentPhone: "+1 (404) 555-0142",
    package: "Group",
    sessionsRemaining: 7,
    sessionsTotal: 12,
    paymentStatus: "Paid",
    joinedAt: "2025-09-12",
    coach: "Coach Yinka Jonny",
    level: "Advanced",
    progressNotes: [
      "Sharp left-foot turn — needs reps under pressure.",
      "First-touch into space improving rapidly.",
    ],
    avatarColor: color(0),
  },
  {
    id: "p_002",
    name: "Liam Okafor",
    age: 9,
    parentName: "Chioma Okafor",
    parentEmail: "chioma@example.com",
    parentPhone: "+1 (404) 555-0118",
    package: "Group",
    sessionsRemaining: 2,
    sessionsTotal: 8,
    paymentStatus: "Unpaid",
    joinedAt: "2025-10-01",
    coach: "Coach Yinka Jonny",
    level: "Intermediate",
    progressNotes: ["Working on scanning before receiving."],
    avatarColor: color(1),
  },
  {
    id: "p_003",
    name: "Zara Mensah",
    age: 13,
    parentName: "Kwame Mensah",
    parentEmail: "kwame@example.com",
    parentPhone: "+1 (404) 555-0133",
    package: "Private",
    sessionsRemaining: 4,
    sessionsTotal: 6,
    paymentStatus: "Paid",
    joinedAt: "2025-08-22",
    coach: "Coach Yinka Jonny",
    level: "Elite",
    progressNotes: [
      "Composure in tight spaces is elite-level.",
      "Add weak-foot finishing reps.",
    ],
    avatarColor: color(2),
  },
  {
    id: "p_004",
    name: "Noah Bennett",
    age: 10,
    parentName: "Sarah Bennett",
    parentEmail: "sarah@example.com",
    parentPhone: "+1 (404) 555-0166",
    package: "Group",
    sessionsRemaining: 9,
    sessionsTotal: 12,
    paymentStatus: "Paid",
    joinedAt: "2025-09-30",
    coach: "Coach Yinka Jonny",
    level: "Intermediate",
    progressNotes: ["Loves the Cruyff — needs disguise."],
    avatarColor: color(3),
  },
  {
    id: "p_005",
    name: "Aaliyah Reid",
    age: 12,
    parentName: "Dwayne Reid",
    parentEmail: "dwayne@example.com",
    parentPhone: "+1 (404) 555-0181",
    package: "Group",
    sessionsRemaining: 0,
    sessionsTotal: 8,
    paymentStatus: "Unpaid",
    joinedAt: "2025-07-14",
    coach: "Coach Yinka Jonny",
    level: "Advanced",
    progressNotes: ["Renewal conversation needed."],
    avatarColor: color(4),
  },
  {
    id: "p_006",
    name: "Ethan Park",
    age: 8,
    parentName: "Jin Park",
    parentEmail: "jin@example.com",
    parentPhone: "+1 (404) 555-0190",
    package: "Camp",
    sessionsRemaining: 3,
    sessionsTotal: 5,
    paymentStatus: "Paid",
    joinedAt: "2025-10-20",
    coach: "Coach Yinka Jonny",
    level: "Beginner",
    progressNotes: ["First-touch confidence is building."],
    avatarColor: color(5),
  },
];

export const todaySessions: Session[] = [
  {
    id: "s_001",
    title: "U10 Ball Mastery — Group A",
    date: "2026-05-14",
    startTime: "16:30",
    endTime: "17:45",
    location: "Piedmont Park · Pitch 3",
    coach: "Coach Yinka Jonny",
    capacity: 14,
    enrolled: ["p_001", "p_002", "p_004", "p_006"],
    attended: [],
    type: "Group",
    notes: "Focus block: 2-touch combinations under pressure.",
  },
  {
    id: "s_002",
    title: "Private — Zara M.",
    date: "2026-05-14",
    startTime: "18:00",
    endTime: "19:00",
    location: "Strive HQ · Indoor Box",
    coach: "Coach Yinka Jonny",
    capacity: 1,
    enrolled: ["p_003"],
    attended: [],
    type: "Private",
  },
  {
    id: "s_003",
    title: "U13 Composure Lab",
    date: "2026-05-14",
    startTime: "19:15",
    endTime: "20:30",
    location: "Piedmont Park · Pitch 3",
    coach: "Coach Yinka Jonny",
    capacity: 12,
    enrolled: ["p_003", "p_005"],
    attended: [],
    type: "Group",
  },
];

export const upcomingSessions: Session[] = [
  {
    id: "s_010",
    title: "U10 Ball Mastery — Group A",
    date: "2026-05-16",
    startTime: "10:00",
    endTime: "11:15",
    location: "Piedmont Park · Pitch 3",
    coach: "Coach Yinka Jonny",
    capacity: 14,
    enrolled: ["p_001", "p_002", "p_004"],
    attended: [],
    type: "Group",
  },
  {
    id: "s_011",
    title: "Half-Term Camp Day 1",
    date: "2026-05-18",
    startTime: "09:00",
    endTime: "12:00",
    location: "Westside Sports Complex",
    coach: "Coach Yinka Jonny",
    capacity: 24,
    enrolled: ["p_006"],
    attended: [],
    type: "Camp",
  },
];

export const leads: Lead[] = [
  {
    id: "l_001",
    name: "Jordan Hayes",
    source: "TikTok",
    interest: "Group Training",
    createdAt: "2026-05-13T18:22:00Z",
    status: "New",
  },
  {
    id: "l_002",
    name: "Priya Shah",
    source: "Instagram",
    interest: "Course",
    createdAt: "2026-05-13T14:01:00Z",
    status: "Contacted",
  },
  {
    id: "l_003",
    name: "Marcus Lewis",
    source: "Referral",
    interest: "Private",
    createdAt: "2026-05-12T20:11:00Z",
    status: "Trial Booked",
  },
  {
    id: "l_004",
    name: "Olivia Tran",
    source: "GHL Form",
    interest: "Camp",
    createdAt: "2026-05-12T11:08:00Z",
    status: "New",
  },
];

export const coachTasks: CoachTask[] = [
  {
    id: "t_001",
    title: "Send Aaliyah's renewal offer",
    due: "Today",
    priority: "High",
    done: false,
    owner: "Coach Yinka Jonny",
  },
  {
    id: "t_002",
    title: "Film 3 Cruyff turn variations for TikTok",
    due: "Today",
    priority: "Med",
    done: false,
    owner: "Coach Yinka Jonny",
  },
  {
    id: "t_003",
    title: "Confirm pitch booking for half-term camp",
    due: "Tomorrow",
    priority: "High",
    done: false,
    owner: "Ops",
  },
  {
    id: "t_004",
    title: "Upload Module 4 voiceover to course",
    due: "Fri",
    priority: "Med",
    done: true,
    owner: "Coach Yinka Jonny",
  },
];

export const courseModules: CourseModule[] = [
  {
    id: "m_01",
    index: 1,
    title: "Foundations — The First Touch",
    description: "The single most underrated skill in football.",
    durationMin: 38,
    locked: false,
    lessons: [
      { id: "l1", title: "Why first touch decides everything", durationSec: 240, completed: true, type: "Video" },
      { id: "l2", title: "Cushion vs. directional touch", durationSec: 360, completed: true, type: "Video" },
      { id: "l3", title: "Wall drill · 200 touches", durationSec: 600, completed: true, type: "Drill" },
      { id: "l4", title: "Daily Challenge: 50 first touches", durationSec: 300, completed: false, type: "Challenge" },
    ],
  },
  {
    id: "m_02",
    index: 2,
    title: "Ball Mastery Vocabulary",
    description: "20 moves every modern player must own.",
    durationMin: 54,
    locked: false,
    lessons: [
      { id: "l5", title: "Sole rolls & toe taps", durationSec: 320, completed: true, type: "Video" },
      { id: "l6", title: "Inside-outside V", durationSec: 360, completed: false, type: "Video" },
      { id: "l7", title: "Cruyff with disguise", durationSec: 420, completed: false, type: "Drill" },
      { id: "l8", title: "Daily Challenge: 20-move flow", durationSec: 240, completed: false, type: "Challenge" },
    ],
  },
  {
    id: "m_03",
    index: 3,
    title: "Composure Under Pressure",
    description: "Slow the game down. Think before you receive.",
    durationMin: 47,
    locked: false,
    lessons: [
      { id: "l9", title: "Scanning every 2 seconds", durationSec: 400, completed: false, type: "Video" },
      { id: "l10", title: "Half-turn principles", durationSec: 360, completed: false, type: "Video" },
      { id: "l11", title: "1v1 escape patterns", durationSec: 480, completed: false, type: "Drill" },
    ],
  },
  {
    id: "m_04",
    index: 4,
    title: "Creativity & Disguise",
    description: "How great players make defenders guess wrong.",
    durationMin: 42,
    locked: true,
    lessons: [
      { id: "l12", title: "Body feints that actually work", durationSec: 380, completed: false, type: "Video" },
      { id: "l13", title: "The art of the no-look pass", durationSec: 340, completed: false, type: "Video" },
    ],
  },
  {
    id: "m_05",
    index: 5,
    title: "Game Intelligence",
    description: "Read the game two passes ahead.",
    durationMin: 51,
    locked: true,
    lessons: [
      { id: "l14", title: "Pattern recognition", durationSec: 420, completed: false, type: "Video" },
      { id: "l15", title: "Decision-making frameworks", durationSec: 460, completed: false, type: "Video" },
    ],
  },
];

export const contentItems: ContentItem[] = [
  {
    id: "c_001",
    title: "3 Touches Most Kids Skip",
    hook: "If you can't do this — you're not training, you're guessing.",
    caption:
      "Most players skip the boring stuff. Then wonder why they freeze under pressure. Master the basics or get exposed. 🎯⚽️ #ballmastery #soccertraining",
    script:
      "[0-2s] Slow-mo of perfect first touch.\n[2-4s] Cut to chaotic kid losing the ball.\n[4-7s] Voiceover: 'Most players skip the basics.'\n[7-12s] Three drill demos, snappy cuts.\n[12-15s] CTA: Link in bio for the full method.",
    platform: "TikTok",
    status: "Viral",
    postedAt: "2026-05-08",
    views: 412000,
    likes: 38700,
    shares: 4210,
    saves: 9120,
    pillar: "Ball Mastery",
  },
  {
    id: "c_002",
    title: "Why Slow Players Win",
    hook: "The fastest player on the pitch isn't the one running the most.",
    caption: "Composure > chaos. Slow the game down. #footballiq #strivesoccer",
    script: "",
    platform: "TikTok",
    status: "Edited",
    pillar: "Mindset",
  },
  {
    id: "c_003",
    title: "Zara's Cruyff Combo",
    hook: "She's 13. Watch how she sets this up.",
    caption: "Composure is taught. Creativity is unlocked. #playerspotlight",
    script: "",
    platform: "Instagram",
    status: "Scripted",
    pillar: "Player Spotlight",
  },
  {
    id: "c_004",
    title: "The 5-Minute Daily Touch Plan",
    hook: "5 minutes a day for 30 days. Results no parent will believe.",
    caption: "",
    script: "",
    platform: "TikTok",
    status: "Idea",
    pillar: "Education",
  },
  {
    id: "c_005",
    title: "Inside a Strive Session",
    hook: "This is what real training looks like.",
    caption: "No cone-tapping. No fluff. Real reps under real pressure.",
    script: "",
    platform: "YouTube Shorts",
    status: "Posted",
    postedAt: "2026-05-11",
    views: 18400,
    likes: 1320,
    shares: 88,
    saves: 410,
    pillar: "Behind the Scenes",
  },
  {
    id: "c_006",
    title: "The 1% Habit That Builds Pros",
    hook: "Pros don't do different things. They do the same things — every single day.",
    caption: "",
    script: "",
    platform: "TikTok",
    status: "Idea",
    pillar: "Mindset",
  },
];

export const stats = {
  monthlyRevenue: 18420,
  revenueDelta: 0.14,
  activeClients: 47,
  activeClientsDelta: 0.08,
  courseSales: 132,
  courseSalesDelta: 0.21,
  newLeads7d: 23,
  leadsDelta: 0.32,
  sessionsThisWeek: 19,
  attendanceRate: 0.94,
  viralPostsLast30: 3,
  contentReachLast30: 1240000,
};

export function getPlayerById(id: string): Player | undefined {
  return players.find((p) => p.id === id);
}

export function unpaidPlayers(): Player[] {
  return players.filter((p) => p.paymentStatus !== "Paid");
}
