import { supabase } from "@/lib/supabase";
import { PageHeader } from "@/components/PageHeader";

export const revalidate = 0;

type Lead = {
  id: string;
    name: string;
      first_name: string | null;
        last_name: string | null;
          email: string | null;
            phone: string | null;
              source: string;
                interest: string;
                  status: string;
                    tags: string[] | null;
                      created_at: string;
                      };

                      async function getLeads(): Promise<Lead[]> {
                        try {
                            const db = supabase();
                                const { data, error } = await db
                                      .from("leads")
                                            .select("*")
                                                  .order("created_at", { ascending: false });
                                                      if (error) throw error;
                                                          return (data as Lead[]) ?? [];
                                                            } catch {
                                                                return [];
                                                                  }
                                                                  }

                                                                  export default async function LeadsPage() {
                                                                    const leads = await getLeads();
                                                                      return (
                                                                          <div>
                                                                                <PageHeader
                                                                                        eyebrow="Leads"
                                                                                                title="Every lead from GHL."
                                                                                                        subtitle="Contacts synced automatically from GoHighLevel when created."
                                                                                                              />
                                                                                                                    <div className="card overflow-hidden">
                                                                                                                            <div className="hidden grid-cols-12 gap-3 border-b border-white/5 px-5 py-3 text-[10px] uppercase tracking-[0.18em] text-muted md:grid">
                                                                                                                                      <div className="col-span-3">Name</div>
                                                                                                                                                <div className="col-span-3">Contact</div>
                                                                                                                                                          <div className="col-span-2">Source</div>
                                                                                                                                                                    <div className="col-span-2">Interest</div>
                                                                                                                                                                              <div className="col-span-2">Status</div>
                                                                                                                                                                                      </div>
                                                                                                                                                                                              {leads.length === 0 ? (
                                                                                                                                                                                                        <div className="px-5 py-12 text-center text-muted">
                                                                                                                                                                                                                    No leads yet. Create a contact in GoHighLevel to see it here.
                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                      ) : (
                                                                                                                                                                                                                                                leads.map((lead) => (
                                                                                                                                                                                                                                                            <div
                                                                                                                                                                                                                                                                          key={lead.id}
                                                                                                                                                                                                                                                                                        className="grid grid-cols-1 gap-3 border-b border-white/5 px-5 py-4 last:border-b-0 md:grid-cols-12"
                                                                                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                                                                                  <div className="col-span-3 flex items-center gap-3">
                                                                                                                                                                                                                                                                                                                                  <div className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-accent/20 text-xs font-bold text-accent">
                                                                                                                                                                                                                                                                                                                                                    {(lead.first_name?.[0] ?? lead.name[0] ?? "?").toUpperCase()}
                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                    <div>
                                                                                                                                                                                                                                                                                                                                                                                                      <div className="font-semibold">{lead.name || "Unknown"}</div>
                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="text-xs text-muted">
                                                                                                                                                                                                                                                                                                                                                                                                                                            {new Date(lead.created_at).toLocaleDateString()}
                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="col-span-3 flex flex-col justify-center gap-0.5">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {lead.email && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="truncate text-xs text-muted">{lead.email}</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {lead.phone && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="text-xs text-muted">{lead.phone}</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="col-span-2 flex items-center">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <span className="chip">{lead.source}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="col-span-2 flex items-center text-xs text-muted">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {lead.interest}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="col-span-2 flex items-center">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <span
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    className={
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        lead.status === "Converted"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ? "chip-accent"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    : lead.status === "Lost"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ? "chip border-red-500/20 bg-red-500/10 text-red-300"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                : "chip border-yellow-500/20 bg-yellow-500/10 text-yellow-300"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {lead.status}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
